memeapi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memes.urls')),
]

memes/urls.py
from django.urls import path, include
from .views import home

app_name = "memes"

urlpatterns = [
    path('', home, name='home')
]

memes/models.py
from django.db import models

# Create your models here.

memes/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse

# Create your views here.
def home(request):
    return render(request,'home.html',{})

memes/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="mt-10 mb-5 flex-wrap d-flex" id="memes-container">
       
</section>
<div class="center">
    <input id="more-button" type="button" class="button bg-dark-blue b-ablue" value="More" style="text-align: center;">
</div>
<br>
<br>
{% endblock %}

{% block script %} 
<script src="{% static 'memes/js/memegenerator.js' %}"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Meme Banget{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% block style %}{% endblock %}
  </head>
  <body>
    <div id="container" class="position-relative">
      <!-- Navbar -->
      <div class="fixed-top bg-dark-blue">
        <nav class="navbar navbar-default navbar-expand-md navbar-light">
          <a class="navbar-brand ml-3" href="{% url 'memes:home' %}" style="color: aliceblue;">Meme Banget</a>
          <button class="navbar-toggler bg-white" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="ml-auto navbar-nav mr-3">
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'home' %} active{% endif %} mr-3" href="{% url 'memes:home' %}" style="color: aliceblue;">Rumah</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
      <!-- Content -->
      {% block content %}{% endblock %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>